import Foundation

/// THE SPEED IN THE AIR, FROM NOTHING A PHONE CAN LOSE (build 112).
///
/// Two things a phone in a bag, in a hand or on a wrist still knows on a plane: how long ago the
/// takeoff roll began (the roll is the largest push it ever feels), and whether the cabin has started
/// down (see FlightPhaseEstimator.descentStartedAt). The speed is what NASA's recorded flights did at
/// that point: the median ground speed of the flights still climbing or cruising in each minute since
/// the roll, then each flight's median cruise speed, and from the top of descent the median speed in
/// each minute since it. Every value is a median of real flights; none is assumed.
///
/// WHY. The build-64 engines read the phone's tilt from the still moment before the roll. On BR215
/// (Taoyuan-Singapore, a 777, graded by its ADS-B track) the iPhone 16 Pro turned over in its bag at
/// the takeoff push; its "tilt" stayed above anything NASA ever flew for 96% of the flight and the
/// network counted 776 km of 2,011. The 17, steadier in a hand, still swung between 0 and 1,700 km/h,
/// because the engines' clock counted only seconds the app was awake and NASA's flights are short.
/// This profile has no tilt and runs on the wall clock. Replayed on BR215 it counts 87% of the
/// 3,397 km flown; held out on NASA's flights, a median of 103% with 62% within 10% (the tilt
/// engines: 102% and 68%, but only with the aircraft's own pitch, which a phone does not have).
///
/// LIMIT. NASA's aircraft is a regional jet that cruised at a median of 760 km/h; BR215's 777
/// cruised at 865-902. Wind and the aircraft type move the real cruise; this is the typical one.
///
/// Generated by flight_profile.py from the 302 NASA DASHlink flights (scratchpad, backed up in
/// ~/Documents/velocity-pipeline). The watch carries an identical copy (scripts/check_watch_engine.sh).
enum FlightProfile {
    /// km/h in each minute since the roll began (index m covers m..m+1 min), while the flights still
    /// climbing or cruising number at least 60.
    static let sinceRoll: [Double] = [
        248, 337, 458, 510, 532, 567, 608, 635, 653, 663, 668, 682, 698, 701, 707, 715, 720, 723, 724,
        726, 732, 728, 732, 735, 737, 735, 741, 744, 754, 756, 758, 765, 762, 762, 762, 767, 768, 765,
        778, 779, 779, 775, 772, 769, 766, 766, 758, 759, 753, 755, 755, 752
    ]
    /// km/h past the end of `sinceRoll`: each flight's median speed between top of climb and top of
    /// descent, the median over the 83 flights that cruised at least 20 minutes.
    static let cruise: Double = 761
    /// km/h in each minute since the top of descent.
    static let sinceDescent: [Double] = [
        716, 701, 686, 678, 663, 646, 623, 602, 580, 564, 547, 533, 522, 503, 481, 481, 473, 453, 444,
        439, 407, 384, 367, 377, 382, 402, 403, 403, 394, 375, 385, 405, 396, 383, 360, 400, 399, 396,
        432
    ]

    /// Ground speed in km/h, `sinceRoll` seconds after the takeoff roll began and, once the cabin has
    /// started down, `sinceDescent` seconds after that.
    static func speedKmh(sinceRoll: TimeInterval, sinceDescent: TimeInterval?) -> Double {
        let m = max(sinceRoll, 0) / 60
        var v = m < Double(Self.sinceRoll.count) ? interpolate(Self.sinceRoll, at: m) : cruise
        if let d = sinceDescent, d >= 0 {
            let vd = interpolate(Self.sinceDescent, at: d / 60)
            v = d < 3600 ? min(v, vd) : vd
        }
        return v
    }

    // THE HEIGHT, THE SAME WAY (build 115). Cabin pressure is not the plane's height (the cabin sat at
    // 1.4-1.6 km while BR215 flew at 9.8-10.4), and acceleration cannot give it (integrated twice it put
    // the plane at 40-97 km after the climb), so the height is NASA's too: the median cruise height of the
    // 83 flights that cruised 20 minutes, reached by the median share of it in each minute since the roll,
    // and left by the median share in each minute since the top of descent. On BR215 it read 1.4 km low
    // in the climb, 0.8 km in cruise and 1.2 km in the descent (ADS-B).

    /// m above the departure runway in cruise.
    static let cruiseAltitude: Double = 8899
    /// Share of the cruise height in each minute since the roll.
    static let climbShare: [Double] = [
        0.004, 0.061, 0.107, 0.172, 0.252, 0.319, 0.371, 0.420, 0.472, 0.524, 0.567, 0.608, 0.648,
        0.688, 0.720, 0.751, 0.776, 0.803, 0.830, 0.859, 0.891, 0.917, 0.939, 0.961, 0.981, 0.993,
        0.999, 0.999, 0.999, 0.999, 0.999, 0.999, 0.999, 0.999, 0.999, 0.999, 0.999, 0.999, 0.999,
        0.999, 0.999, 0.999, 0.999, 0.999, 0.999, 0.999, 0.999, 0.999, 0.999, 0.999, 0.999, 0.999,
        0.999, 0.999, 0.999, 0.999, 0.999, 0.999, 0.999, 0.999
    ]
    /// Share of the cruise height in each minute since the top of descent.
    static let descentShare: [Double] = [
        0.940, 0.890, 0.850, 0.810, 0.783, 0.739, 0.686, 0.640, 0.590, 0.543, 0.473, 0.426, 0.399,
        0.381, 0.355, 0.342, 0.312, 0.279, 0.248, 0.234, 0.191, 0.198, 0.156, 0.170, 0.160, 0.145,
        0.159, 0.135, 0.107, 0.111, 0.104, 0.096, 0.095, 0.110
    ]

    /// Height above the departure runway in metres, timed like `speedKmh`.
    static func altitudeMeters(sinceRoll: TimeInterval, sinceDescent: TimeInterval?) -> Double {
        let m = max(sinceRoll, 0) / 60
        var h = cruiseAltitude * (m < Double(climbShare.count) ? interpolate(climbShare, at: m) : 1)
        if let d = sinceDescent, d >= 0 {
            h = min(h, cruiseAltitude * interpolate(descentShare, at: d / 60))
        }
        return max(h, 0)
    }

    // THE TAKEOFF'S HANDOVER (build 117). When the takeoff measurement ends after liftoff, the plane may be
    // faster or slower than NASA's median then. Across NASA's flights, such a difference at 1-2 minutes after
    // the roll was still 80% there half a minute later, 56% after a minute, about a quarter after two to four,
    // and only noise after that; so it is carried that way and gone by six minutes. In August the measurement
    // handed over at 1.8 minutes at 322 km/h where the median said 376: minutes 1-3 went from 63 to 24 km/h
    // off GPS, minutes 3-5 from 27 to 9. A handover during the roll (BR215: 0.47 minutes) says nothing about
    // the climb (NASA: 16% left after a minute) and is not carried.
    static let carryMinutes: [Double] = [0, 0.5, 1, 2, 3, 4, 6]
    static let carryShare: [Double] = [1.0, 0.80, 0.56, 0.23, 0.21, 0.28, 0.0]
    static let CARRY_FROM: TimeInterval = 45

    /// `speedKmh`, carrying what the takeoff measured when it handed over (`handoverSinceRoll` seconds after the
    /// roll, at `handoverKmh`).
    static func speedKmh(sinceRoll t: TimeInterval, sinceDescent d: TimeInterval?,
                         handoverSinceRoll h: TimeInterval?, handoverKmh vh: Double?) -> Double {
        let base = speedKmh(sinceRoll: t, sinceDescent: d)
        guard let h, let vh, h >= CARRY_FROM, t >= h, let last = carryMinutes.last else { return base }
        let k = (t - h) / 60
        guard k < last else { return base }
        let atHandover = speedKmh(sinceRoll: h, sinceDescent: nil)
        guard atHandover > 0 else { return base }
        let ratio = min(max(vh / atHandover, 0.6), 1.4)
        return base * (1 + (ratio - 1) * linear(carryMinutes, carryShare, at: k))
    }

    private static func linear(_ x: [Double], _ y: [Double], at v: Double) -> Double {
        guard let first = x.first, let last = x.last else { return 0 }
        if v <= first { return y[0] }
        if v >= last { return y[y.count - 1] }
        var i = 0
        while i + 1 < x.count, x[i + 1] < v { i += 1 }
        return y[i] + (y[i + 1] - y[i]) * (v - x[i]) / (x[i + 1] - x[i])
    }

    /// Linear between minute midpoints, held at both ends.
    private static func interpolate(_ a: [Double], at minutes: Double) -> Double {
        guard let first = a.first, let last = a.last else { return 0 }
        let x = minutes - 0.5
        if x <= 0 { return first }
        let i = Int(x)
        if i >= a.count - 1 { return last }
        let f = x - Double(i)
        return a[i] + (a[i + 1] - a[i]) * f
    }
}
