import Foundation

/// THE SPEED IN THE AIR, FROM NOTHING A PHONE CAN LOSE (build 112).
///
/// Two things a phone in a bag, in a hand or on a wrist still knows on a plane: how long ago the
/// takeoff roll began (the roll is the largest push it ever feels), and whether the cabin has started
/// down (see FlightPhaseEstimator.descentStartedAt). The speed is what real airliners did at that point:
/// the median ground speed in each minute since the roll of the flights still climbing or cruising, then
/// the median cruise speed, and from the top of descent the median speed in each minute since it. Every
/// value is a median of real flights; none is assumed.
///
/// THE DATA (build 118): NASA AND OPENSKY, POOLED. Until build 117 these medians came from NASA's DASHlink flight
/// recorders alone: 302 flights of one regional jet, which climbed and cruised slower than an airliner like BR215's
/// 777 (cruise 761 km/h; BR215 865-902). Now they pool those 302 with a full day of the OpenSky Network's worldwide
/// ADS-B state vectors (27 June 2022): 1,194 jet takeoffs (1,034 single-aisle, 160 twin-aisle) whose liftoff was
/// received, each followed across the day's hours to its cruise and, for 1,079 of them, down from the moment it was
/// 300 m below its last cruise level (where BR215's cabin latched). Each flight counts once in each minute. OpenSky
/// brings jets of every size and the long flights; its flights begin at liftoff, so the roll's first minute is
/// NASA's, whose recordings run once a second from the roll. OpenSky's clock is liftoff less NASA's median 25 s from
/// 30 kt.
///
/// Held out by aircraft, on OpenSky flights whose descent was seen the profile counts a median 99% of the distance,
/// within 10% on 72%; on NASA's (a slower jet) 114%. Replayed on BR215 it counts 95% of the 3,392 km flown; on the
/// August flight (GPS) 78.4 km of 77.4. NASA alone: 87% and 77.3; one hour of OpenSky alone: 96% and 77.7, but
/// minutes 5-10 of August 20 km/h off GPS where the pooled profile is 15. OpenSky Network, "Bringing up OpenSky: A
/// large-scale ADS-B sensor network for research", IPSN 2014.
///
/// WHY. The build-64 engines read the phone's tilt from the still moment before the roll. On BR215
/// (Taoyuan-Singapore, a 777, graded by its ADS-B track) the iPhone 16 Pro turned over in its bag at
/// the takeoff push; its "tilt" stayed above anything NASA ever flew for 96% of the flight and the
/// network counted 776 km of 2,011. The 17, steadier in a hand, still swung between 0 and 1,700 km/h,
/// because the engines' clock counted only seconds the app was awake and NASA's flights are short.
/// This profile has no tilt and runs on the wall clock. Replayed on BR215 it counts 87% of the
/// 3,397 km flown; held out on NASA's flights, a median of 103% with 62% within 10% (the tilt
/// engines: 102% and 68%, but only with the aircraft's own pitch, which a phone does not have).
///
/// LIMIT. This is the typical jet. Twin-aisle jets cruised near 905 km/h and single-aisle near 820; a phone cannot
/// tell which it is on, and wind moves every one. Cruise reading on as long as the flight lasts gained nothing: the
/// jets still up after two or three hours flew within 15 km/h of the rest.
///
/// Generated by osday_load.py / osday_flights.py / osday_final.py (--simple), graded by osday_exp3.py (scratchpad,
/// backed up in ~/Documents/velocity-pipeline); the earlier NASA version by flight_profile.py. The watch carries an
/// identical copy (scripts/check_watch_engine.sh).
enum FlightProfile {
    /// km/h in each minute since the roll began (index m covers m..m+1 min): the pooled flights still climbing or
    /// cruising, until the median is within 1% of the cruise.
    static let sinceRoll: [Double] = [
        248, 343, 450, 502, 535, 588, 635, 665, 690, 710, 728, 744, 760, 772, 783, 794, 798, 805, 807,
        809, 810, 811, 813, 814, 816, 818, 818, 820, 820, 818, 820, 820, 821, 822, 822, 822, 823, 823
    ]
    /// km/h past the end of `sinceRoll`: the median of every minute from the 40th on.
    static let cruise: Double = 831
    /// km/h in each minute since the aircraft was 300 m below its last cruise level (the cabin's latch), until it
    /// stops falling: past 33 minutes the few flights left are ones whose descent was misread.
    static let sinceDescent: [Double] = [
        776, 765, 750, 734, 719, 702, 685, 667, 648, 631, 602, 580, 557, 539, 526, 507, 493, 475, 450,
        433, 412, 392, 381, 367, 354, 341, 339, 328, 312, 304, 300, 296, 290
    ]

    /// Ground speed in km/h, `sinceRoll` seconds after the takeoff roll began and, once the cabin has
    /// started down, `sinceDescent` seconds after that.
    static func speedKmh(sinceRoll: TimeInterval, sinceDescent: TimeInterval?) -> Double {
        let m = max(sinceRoll, 0) / 60
        var v = m < Double(Self.sinceRoll.count) ? interpolate(Self.sinceRoll, at: m) : cruise
        if let d = sinceDescent, d >= 0 {
            let vd = interpolate(Self.sinceDescent, at: d / 60)
            v = d < 3600 ? min(v, vd) : vd
        }
        return v
    }

    // THE HEIGHT, THE SAME WAY (build 115). Cabin pressure is not the plane's height (the cabin sat at
    // 1.4-1.6 km while BR215 flew at 9.8-10.4), and acceleration cannot give it (integrated twice it put
    // the plane at 40-97 km after the climb), so the height is a typical airliner's too: since build 118
    // the pooled flights' median cruise height (10.9 km above the runway), reached by the median share of it in
    // each minute since the roll and left by the median share of the level each flight left in each minute since
    // the latch. Held out, a median of 0.66 km off; a cruise height rising with the flight's length did no better.
    // On BR215 (which cruised low, 9.8-10.4 km): climb 0.6 km low, cruise 1.2 km high, descent 1.2 km (NASA's:
    // 1.4, 0.8 low, 1.2).

    /// m above the departure runway in cruise.
    static let cruiseAltitude: Double = 10909
    /// Share of the cruise height in each minute since the roll.
    static let climbShare: [Double] = [
        0.004, 0.051, 0.102, 0.167, 0.239, 0.294, 0.346, 0.401, 0.455, 0.506, 0.549, 0.591, 0.631,
        0.665, 0.698, 0.729, 0.760, 0.790, 0.819, 0.841, 0.861, 0.881, 0.895, 0.910, 0.920, 0.934,
        0.941, 0.945, 0.950, 0.952, 0.953, 0.954, 0.959, 0.962, 0.963, 0.964, 0.966, 0.967, 0.967,
        0.968, 0.969, 0.970, 0.970, 0.970, 0.970, 0.971, 0.971, 0.972, 0.973, 0.973, 0.974, 0.974,
        0.975, 0.975, 0.976, 0.978, 0.978, 0.980, 0.980, 0.981, 0.981, 0.985, 0.985, 0.986, 0.986,
        0.987, 0.987, 0.987, 0.987, 0.988, 0.988, 0.988, 0.988, 0.989, 0.989, 0.990, 0.990, 0.990,
        0.990
    ]
    /// Share of the level it left in each minute since the latch.
    static let descentShare: [Double] = [
        0.936, 0.877, 0.816, 0.757, 0.703, 0.649, 0.594, 0.541, 0.493, 0.446, 0.403, 0.364, 0.329,
        0.298, 0.267, 0.240, 0.211, 0.188, 0.167, 0.152, 0.133, 0.113, 0.106, 0.093, 0.084, 0.074,
        0.074, 0.072, 0.071, 0.060, 0.052, 0.060, 0.060
    ]

    /// Height above the departure runway in metres, timed like `speedKmh`.
    static func altitudeMeters(sinceRoll: TimeInterval, sinceDescent: TimeInterval?) -> Double {
        let m = max(sinceRoll, 0) / 60
        var h = cruiseAltitude * (m < Double(climbShare.count) ? interpolate(climbShare, at: m) : 1)
        if let d = sinceDescent, d >= 0 {
            h = min(h, cruiseAltitude * interpolate(descentShare, at: d / 60))
        }
        return max(h, 0)
    }

    // THE TAKEOFF'S HANDOVER (build 117). When the takeoff measurement ends after liftoff, the plane may be
    // faster or slower than the median then. How much of such a difference at 1.8 minutes after the roll is still
    // there later was measured on NASA's flights (once a second) and on OpenSky's (every 10 s) apart, and they
    // agree: 81% and 87% half a minute later, 50% and 60% after a minute, 21% and 30% after two, about a third at
    // three to four. Pooled (build 118) the shares below; a little (2-7%) is still there 8-20 minutes on, where
    // build 117 stopped at six. In August the measurement handed over at 1.8 minutes at 322 km/h where the median
    // said 375: minutes 5-10 went from 28 to 15 km/h off GPS with the longer carry. A handover during the roll
    // (BR215: 0.47 minutes) says nothing about the climb (NASA: 16% left after a minute) and is not carried.
    static let carryMinutes: [Double] = [0, 0.5, 1, 2, 3, 4, 6, 8, 10, 12, 15, 20, 25]
    static let carryShare: [Double] = [1.0, 0.86, 0.58, 0.29, 0.32, 0.32, 0.15, 0.07, 0.06, 0.06, 0.04, 0.02, 0.0]
    static let CARRY_FROM: TimeInterval = 45

    /// `speedKmh`, carrying what the takeoff measured when it handed over (`handoverSinceRoll` seconds after the
    /// roll, at `handoverKmh`).
    static func speedKmh(sinceRoll t: TimeInterval, sinceDescent d: TimeInterval?,
                         handoverSinceRoll h: TimeInterval?, handoverKmh vh: Double?) -> Double {
        let base = speedKmh(sinceRoll: t, sinceDescent: d)
        guard let h, let vh, h >= CARRY_FROM, t >= h, let last = carryMinutes.last else { return base }
        let k = (t - h) / 60
        guard k < last else { return base }
        let atHandover = speedKmh(sinceRoll: h, sinceDescent: nil)
        guard atHandover > 0 else { return base }
        let ratio = min(max(vh / atHandover, 0.6), 1.4)
        return base * (1 + (ratio - 1) * linear(carryMinutes, carryShare, at: k))
    }

    private static func linear(_ x: [Double], _ y: [Double], at v: Double) -> Double {
        guard let first = x.first, let last = x.last else { return 0 }
        if v <= first { return y[0] }
        if v >= last { return y[y.count - 1] }
        var i = 0
        while i + 1 < x.count, x[i + 1] < v { i += 1 }
        return y[i] + (y[i + 1] - y[i]) * (v - x[i]) / (x[i + 1] - x[i])
    }

    /// Linear between minute midpoints, held at both ends.
    private static func interpolate(_ a: [Double], at minutes: Double) -> Double {
        guard let first = a.first, let last = a.last else { return 0 }
        let x = minutes - 0.5
        if x <= 0 { return first }
        let i = Int(x)
        if i >= a.count - 1 { return last }
        let f = x - Double(i)
        return a[i] + (a[i + 1] - a[i]) * f
    }
}
