import Foundation

/// THE SPEED IN THE AIR, FROM NOTHING A PHONE CAN LOSE (build 112).
///
/// Two things a phone in a bag, in a hand or on a wrist still knows on a plane: how long ago the
/// takeoff roll began (the roll is the largest push it ever feels), and whether the cabin has started
/// down (see FlightPhaseEstimator.descentStartedAt). The speed is what NASA's recorded flights did at
/// that point: the median ground speed of the flights still climbing or cruising in each minute since
/// the roll, then each flight's median cruise speed, and from the top of descent the median speed in
/// each minute since it. Every value is a median of real flights; none is assumed.
///
/// WHY. The build-64 engines read the phone's tilt from the still moment before the roll. On BR215
/// (Taoyuan-Singapore, a 777, graded by its ADS-B track) the iPhone 16 Pro turned over in its bag at
/// the takeoff push; its "tilt" stayed above anything NASA ever flew for 96% of the flight and the
/// network counted 776 km of 2,011. The 17, steadier in a hand, still swung between 0 and 1,700 km/h,
/// because the engines' clock counted only seconds the app was awake and NASA's flights are short.
/// This profile has no tilt and runs on the wall clock. Replayed on BR215 it counts 87% of the
/// 3,397 km flown; held out on NASA's flights, a median of 103% with 62% within 10% (the tilt
/// engines: 102% and 68%, but only with the aircraft's own pitch, which a phone does not have).
///
/// LIMIT. NASA's aircraft is a regional jet that cruised at a median of 760 km/h; BR215's 777
/// cruised at 865-902. Wind and the aircraft type move the real cruise; this is the typical one.
///
/// Generated by flight_profile.py from the 302 NASA DASHlink flights (scratchpad, backed up in
/// ~/Documents/velocity-pipeline). The watch carries an identical copy (scripts/check_watch_engine.sh).
enum FlightProfile {
    /// km/h in each minute since the roll began (index m covers m..m+1 min), while the flights still
    /// climbing or cruising number at least 60.
    static let sinceRoll: [Double] = [
        248, 337, 458, 510, 532, 567, 608, 635, 653, 663, 668, 682, 698, 701, 707, 715, 720, 723, 724,
        726, 732, 728, 732, 735, 737, 735, 741, 744, 754, 756, 758, 765, 762, 762, 762, 767, 768, 765,
        778, 779, 779, 775, 772, 769, 766, 766, 758, 759, 753, 755, 755, 752
    ]
    /// km/h past the end of `sinceRoll`: each flight's median speed between top of climb and top of
    /// descent, the median over the 83 flights that cruised at least 20 minutes.
    static let cruise: Double = 761
    /// km/h in each minute since the top of descent.
    static let sinceDescent: [Double] = [
        716, 701, 686, 678, 663, 646, 623, 602, 580, 564, 547, 533, 522, 503, 481, 481, 473, 453, 444,
        439, 407, 384, 367, 377, 382, 402, 403, 403, 394, 375, 385, 405, 396, 383, 360, 400, 399, 396,
        432
    ]

    /// Ground speed in km/h, `sinceRoll` seconds after the takeoff roll began and, once the cabin has
    /// started down, `sinceDescent` seconds after that.
    static func speedKmh(sinceRoll: TimeInterval, sinceDescent: TimeInterval?) -> Double {
        let m = max(sinceRoll, 0) / 60
        var v = m < Double(Self.sinceRoll.count) ? interpolate(Self.sinceRoll, at: m) : cruise
        if let d = sinceDescent, d >= 0 {
            let vd = interpolate(Self.sinceDescent, at: d / 60)
            v = d < 3600 ? min(v, vd) : vd
        }
        return v
    }

    /// Linear between minute midpoints, held at both ends.
    private static func interpolate(_ a: [Double], at minutes: Double) -> Double {
        guard let first = a.first, let last = a.last else { return 0 }
        let x = minutes - 0.5
        if x <= 0 { return first }
        let i = Int(x)
        if i >= a.count - 1 { return last }
        let f = x - Double(i)
        return a[i] + (a[i + 1] - a[i]) * f
    }
}
