import Foundation
import HealthKit
import CoreLocation

class HealthKitManager: ObservableObject {
    private let healthStore = HKHealthStore()
    @Published var isAuthorized = false
    private var cachedHeightMeters: Double?
    private let autoGeneratedSampleMetadata: [String: Any] = [
        HKMetadataKeyWasUserEntered: false
    ]

    // HealthKit types we need permission for
    private let typesToShare: Set<HKSampleType> = [
        HKObjectType.workoutType(),
        HKSeriesType.workoutRoute(),
        HKQuantityType.quantityType(forIdentifier: .heartRate)!,
        HKQuantityType.quantityType(forIdentifier: .activeEnergyBurned)!,
        HKQuantityType.quantityType(forIdentifier: .basalEnergyBurned)!,
        HKQuantityType.quantityType(forIdentifier: .distanceWalkingRunning)!,
        HKQuantityType.quantityType(forIdentifier: .distanceCycling)!,
        // Speed/Pace
        HKQuantityType.quantityType(forIdentifier: .runningSpeed)!,
        HKQuantityType.quantityType(forIdentifier: .cyclingSpeed)!,
        // ADVANCED METRICS: Running dynamics (auto-collected by HKLiveWorkoutDataSource if sensors available)
        HKQuantityType.quantityType(forIdentifier: .runningPower)!,
        HKQuantityType.quantityType(forIdentifier: .runningStrideLength)!,
        HKQuantityType.quantityType(forIdentifier: .walkingStepLength)!,
        HKQuantityType.quantityType(forIdentifier: .runningVerticalOscillation)!,
        HKQuantityType.quantityType(forIdentifier: .runningGroundContactTime)!,
        // ADVANCED METRICS: Cadence
        HKQuantityType.quantityType(forIdentifier: .stepCount)!,
        HKQuantityType.quantityType(forIdentifier: .cyclingCadence)!
    ]

    private let typesToRead: Set<HKObjectType> = [
        HKObjectType.workoutType(),
        HKSeriesType.workoutRoute(),
        HKQuantityType.quantityType(forIdentifier: .heartRate)!,
        HKQuantityType.quantityType(forIdentifier: .activeEnergyBurned)!,
        HKQuantityType.quantityType(forIdentifier: .basalEnergyBurned)!,
        HKQuantityType.quantityType(forIdentifier: .distanceWalkingRunning)!,
        HKQuantityType.quantityType(forIdentifier: .distanceCycling)!,
        HKQuantityType.quantityType(forIdentifier: .height)!,
        // Speed/Pace
        HKQuantityType.quantityType(forIdentifier: .runningSpeed)!,
        HKQuantityType.quantityType(forIdentifier: .cyclingSpeed)!,
        // ADVANCED METRICS: Running dynamics
        HKQuantityType.quantityType(forIdentifier: .runningPower)!,
        HKQuantityType.quantityType(forIdentifier: .runningStrideLength)!,
        HKQuantityType.quantityType(forIdentifier: .walkingStepLength)!,
        HKQuantityType.quantityType(forIdentifier: .runningVerticalOscillation)!,
        HKQuantityType.quantityType(forIdentifier: .runningGroundContactTime)!,
        // ADVANCED METRICS: Cadence
        HKQuantityType.quantityType(forIdentifier: .stepCount)!,
        HKQuantityType.quantityType(forIdentifier: .cyclingCadence)!
    ]

    func requestAuthorization(completion: @escaping (Bool, Error?) -> Void) {
        guard HKHealthStore.isHealthDataAvailable() else {
            let error = NSError(domain: "HealthKit", code: -1, userInfo: [NSLocalizedDescriptionKey: "HealthKit is not available on this device"])
            DispatchQueue.main.async {
                completion(false, error)
            }
            return
        }

        print("🏥 [Watch] Requesting HealthKit authorization...")

        // CRITICAL: requestAuthorization completion runs on BACKGROUND THREAD
        // Must dispatch all UI updates to main thread to avoid crashes
        healthStore.requestAuthorization(toShare: typesToShare, read: typesToRead) { [weak self] success, error in
            print("🏥 [Watch] HealthKit authorization result: \(success ? "✅ Success" : "❌ Failed")")
            if let error = error {
                print("🏥 [Watch] HealthKit error: \(error.localizedDescription)")
            }

            // MUST run on main thread to update @Published properties
            DispatchQueue.main.async {
                self?.isAuthorized = success
                completion(success, error)
            }
        }
    }

    func saveWorkout(
        flight: Flight,
        locations: [FlightLocation],
        metrics: FlightMetrics,
        completion: @escaping (Bool, Error?) -> Void
    ) {
        saveWorkoutWithResult(flight: flight, locations: locations, metrics: metrics) { success, error, _ in
            completion(success, error)
        }
    }

    func saveWorkoutWithResult(
        flight: Flight,
        locations: [FlightLocation],
        metrics: FlightMetrics,
        completion: @escaping (Bool, Error?, HKWorkout?) -> Void
    ) {
        guard isAuthorized else {
            completion(false, NSError(domain: "HealthKit", code: -1, userInfo: [NSLocalizedDescriptionKey: "HealthKit not authorized"]), nil)
            return
        }

        guard let endDate = flight.endDate else {
            completion(false, NSError(domain: "HealthKit", code: -1, userInfo: [NSLocalizedDescriptionKey: "Flight has no end date"]), nil)
            return
        }

        // Create workout configuration
        let configuration = HKWorkoutConfiguration()
        let resolvedType: HKWorkoutActivityType
        if let rawValue = flight.workoutType,
           let activityType = HKWorkoutActivityType(rawValue: rawValue) {
            resolvedType = activityType
        } else {
            resolvedType = .walking
        }
        configuration.activityType = exportActivityType(resolvedType)
        configuration.locationType = .outdoor

        // Create workout builder
        let builder = HKWorkoutBuilder(healthStore: healthStore, configuration: configuration, device: .local())

        // Begin collection
        builder.beginCollection(withStart: flight.startDate) { success, error in
            guard success else {
                completion(false, error, nil)
                return
            }

            // Add metadata including HealthKit standard elevation keys
            var metadata: [String: Any] = [
                "origin": flight.origin ?? "Unknown",
                "destination": flight.destination ?? "Unknown",
                "maxAltitude": metrics.maxAltitude,
                "minAltitude": metrics.minAltitude,
                "maxSpeed": metrics.maxSpeed,
                "averageAccuracy": metrics.averageAccuracy,
                "com.exmstc.gps.gpsDistanceMeters": metrics.totalDistance
            ]
            if let nativeStepDistance = metrics.nativeStepDistance, nativeStepDistance > 0 {
                metadata["com.exmstc.gps.nativeStepDistanceMeters"] = nativeStepDistance
            }
            if let stepCount = metrics.stepsCount, stepCount > 0 {
                metadata["com.exmstc.gps.nativeStepCount"] = stepCount
            }
            if let effort = flight.effort {
                metadata["effort"] = effort
                print("⌚ 🧮 Adding effort to HealthKit metadata: \(effort)/10")
            } else {
                print("⌚ ⚠️ Effort missing - no effort metadata will be saved")
            }
            metadata[HKMetadataKeyTimeZone] = TimeZone.current.identifier
            let nativeStepDistanceText = metrics.nativeStepDistance.map { String(format: "%.2f", $0) } ?? "nil"
            let nativeStepCountText = metrics.stepsCount.map { String(format: "%.0f", $0) } ?? "nil"
            print("⌚ 🧭 HealthKit channels: gpsDistance=\(String(format: "%.2f", metrics.totalDistance))m, nativeSteps=\(nativeStepCountText), nativeStepDistance=\(nativeStepDistanceText)m")

            // Add average speed metadata (HealthKit standard key)
            if metrics.averageSpeed > 0 {
                let avgSpeedQuantity = HKQuantity(unit: HKUnit.meter().unitDivided(by: .second()), doubleValue: metrics.averageSpeed)
                metadata[HKMetadataKeyAverageSpeed] = avgSpeedQuantity
                print("⌚ 📊 Adding average speed: \(String(format: "%.1f", metrics.averageSpeed * 3.6)) km/h")
            }

            // Add max speed metadata
            if metrics.maxSpeed > 0 {
                let maxSpeedQuantity = HKQuantity(unit: HKUnit.meter().unitDivided(by: .second()), doubleValue: metrics.maxSpeed)
                metadata[HKMetadataKeyMaximumSpeed] = maxSpeedQuantity
                print("⌚ 📊 Adding max speed: \(String(format: "%.1f", metrics.maxSpeed * 3.6)) km/h")
            }

            // Add HealthKit standard elevation metadata (required for Fitness app)
            if metrics.totalAltitudeGain > 0 {
                metadata[HKMetadataKeyElevationAscended] = HKQuantity(unit: .meter(), doubleValue: metrics.totalAltitudeGain)
                print("⌚ 📊 Adding elevation ascended: \(String(format: "%.1f", metrics.totalAltitudeGain))m")
            }
            if metrics.totalAltitudeLoss > 0 {
                metadata[HKMetadataKeyElevationDescended] = HKQuantity(unit: .meter(), doubleValue: metrics.totalAltitudeLoss)
                print("⌚ 📊 Adding elevation descended: \(String(format: "%.1f", metrics.totalAltitudeLoss))m")
            }

            print("⌚ 📊 Workout metadata: maxAlt=\(String(format: "%.1f", metrics.maxAltitude))m, minAlt=\(String(format: "%.1f", metrics.minAltitude))m")

            builder.addMetadata(metadata) { success, error in
                guard success else {
                    completion(false, error, nil)
                    return
                }

                let exportType = self.exportActivityType(configuration.activityType)
                self.addWorkoutSamples(
                    to: builder,
                    metrics: metrics,
                    activityType: exportType,
                    locations: locations
                ) {
                    self.addCaloriesAndStepsSamples(
                        to: builder,
                        metrics: metrics,
                        startDate: flight.startDate,
                        endDate: endDate,
                        activityType: exportType
                    ) {
                        self.addDistanceSamplesIfMissing(
                            to: builder,
                            metrics: metrics,
                            startDate: flight.startDate,
                            endDate: endDate,
                            activityType: exportType
                        ) {
                            // End collection
                            builder.endCollection(withEnd: endDate) { success, error in
                                guard success else {
                                    completion(false, error, nil)
                                    return
                                }

                                // Finish workout
                                builder.finishWorkout { workout, error in
                                    if let workout = workout {
                                        // Now save the route
                                        self.saveRoute(for: workout, locations: locations) { success, routeError in
                                            completion(success, routeError, workout)
                                        }
                                    } else {
                                        completion(false, error, nil)
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    // MARK: - Add Workout Samples (Speed + Running Dynamics)

    func addWorkoutSamples(
        to builder: HKWorkoutBuilder,
        metrics: FlightMetrics,
        activityType: HKWorkoutActivityType,
        locations: [FlightLocation],
        completion: @escaping () -> Void
    ) {
        let speedSamples = buildSpeedSamples(metrics: metrics, activityType: activityType)
        let advancedSamples = buildAdvancedMetricSamples(metrics: metrics, activityType: activityType, locations: locations)
        let allSamples = speedSamples + advancedSamples

        guard !allSamples.isEmpty else {
            print("⌚ ⚠️ No workout samples to add (empty)")
            completion()
            return
        }

        print("⌚ 📊 Adding \(speedSamples.count) speed samples and \(advancedSamples.count) advanced metric samples")

        // Add samples in batches for better reliability with long workouts
        let batchSize = 50
        var currentIndex = 0

        func addNextBatch() {
            let endIndex = min(currentIndex + batchSize, allSamples.count)
            let batch = Array(allSamples[currentIndex..<endIndex])

            let batchNumber = currentIndex/batchSize + 1
            let totalBatches = (allSamples.count + batchSize - 1) / batchSize

            if totalBatches > 1 {
                print("⌚    Adding sample batch \(batchNumber)/\(totalBatches): samples \(currentIndex+1) to \(endIndex)")
            }

            builder.add(batch) { success, error in
                if success {
                    currentIndex = endIndex
                    if currentIndex < allSamples.count {
                        // Add next batch
                        addNextBatch()
                    } else {
                        // All batches added
                        print("⌚ ✅ All workout samples added successfully")
                        completion()
                    }
                } else {
                    print("⌚ ⚠️ Failed to add workout sample batch \(batchNumber): \(error?.localizedDescription ?? "Unknown")")
                    // Continue anyway - don't fail the entire workout
                    completion()
                }
            }
        }

        addNextBatch()
    }

    func addCaloriesAndStepsSamples(
        to builder: HKWorkoutBuilder,
        metrics: FlightMetrics,
        startDate: Date,
        endDate: Date,
        activityType: HKWorkoutActivityType,
        completion: @escaping () -> Void
    ) {
        print("⌚ 📊 addCaloriesAndStepsSamples called:")
        print("   Calories: \(String(format: "%.0f", metrics.caloriesBurned)) kcal")
        print("   Activity Type: \(activityType.rawValue) (\(activityType == .walking ? "Walking" : activityType == .running ? "Running" : activityType == .cycling ? "Cycling" : "Other"))")
        if let nativeStepDistance = metrics.nativeStepDistance {
            print("   👟 Native pedometer distance: \(String(format: "%.2f", nativeStepDistance))m")
        } else {
            print("   👟 Native pedometer distance: not available")
        }

        var samples: [HKQuantitySample] = []

        // Add active energy (native from HKLiveWorkoutDataSource)
        if metrics.caloriesBurned > 0 {
            if let energyType = HKQuantityType.quantityType(forIdentifier: .activeEnergyBurned) {
                let energySample = HKQuantitySample(
                    type: energyType,
                    quantity: HKQuantity(unit: .kilocalorie(), doubleValue: metrics.caloriesBurned),
                    start: startDate,
                    end: endDate,
                    metadata: autoGeneratedSampleMetadata
                )
                samples.append(energySample)
                print("   🔥 Active Energy: \(String(format: "%.0f", metrics.caloriesBurned)) kcal")
            }
        }

        // Add resting energy if available
        if metrics.restingEnergyBurned > 0 {
            if let basalType = HKQuantityType.quantityType(forIdentifier: .basalEnergyBurned) {
                let basalSample = HKQuantitySample(
                    type: basalType,
                    quantity: HKQuantity(unit: .kilocalorie(), doubleValue: metrics.restingEnergyBurned),
                    start: startDate,
                    end: endDate,
                    metadata: autoGeneratedSampleMetadata
                )
                samples.append(basalSample)
                print("   💤 Resting Energy: \(String(format: "%.0f", metrics.restingEnergyBurned)) kcal")
            }
        }

        func finish(withStepSources stepSources: [(count: Double, source: String)]) {
            if let stepType = HKQuantityType.quantityType(forIdentifier: .stepCount) {
                for stepSource in stepSources where stepSource.count > 0 {
                    print("   👟 Step source: \(stepSource.source) = \(String(format: "%.0f", stepSource.count))")
                    let distributedSamples = makeDistributedStepSamples(
                        stepType: stepType,
                        totalSteps: stepSource.count,
                        startDate: startDate,
                        endDate: endDate
                    )
                    if distributedSamples.isEmpty {
                        let stepSample = HKQuantitySample(
                            type: stepType,
                            quantity: HKQuantity(unit: .count(), doubleValue: stepSource.count),
                            start: startDate,
                            end: endDate,
                            metadata: autoGeneratedSampleMetadata
                        )
                        samples.append(stepSample)
                    } else {
                        print("   👟 Writing distributed step samples: \(distributedSamples.count) segments")
                        samples.append(contentsOf: distributedSamples)
                    }
                }
            }

            if stepSources.isEmpty {
                print("   👟 No steps available - skipping step sample")
            }

            guard !samples.isEmpty else {
                print("⌚ ⚠️ No calorie/step samples to add (samples array is empty)")
                completion()
                return
            }

            print("⌚ 📊 About to add \(samples.count) calorie/step samples")

            builder.add(samples) { success, error in
                if success {
                    print("⌚ ✅ Calorie/step samples added successfully")
                } else {
                    print("⌚ ❌ Failed to add calorie/step samples: \(error?.localizedDescription ?? "Unknown")")
                }
                completion()
            }
        }

        // Add step count. For walking/running/hiking we send BOTH native and GPS-estimated channels.
        let nativeSteps = (metrics.stepsCount ?? 0) > 0 ? (metrics.stepsCount ?? 0) : 0
        let isStepBasedActivity = (activityType == .walking || activityType == .running || activityType == .hiking)

        if !isStepBasedActivity {
            if nativeSteps > 0 {
                print("   👟 Using native pedometer steps: \(String(format: "%.0f", nativeSteps)) steps")
                finish(withStepSources: [(nativeSteps, "pedometer-native")])
            } else {
                finish(withStepSources: [])
            }
            return
        }

        guard metrics.totalDistance > 0 || nativeSteps > 0 else {
            finish(withStepSources: [])
            return
        }

        resolveStrideLength(activityType: activityType) { strideLength in
            var stepSources: [(count: Double, source: String)] = []

            if nativeSteps > 0 {
                print("   👟 Native pedometer steps available: \(String(format: "%.0f", nativeSteps))")
                stepSources.append((nativeSteps, "pedometer-native"))
            } else {
                print("   👟 Native pedometer steps unavailable - using GPS estimation channel only")
            }

            if metrics.totalDistance > 0 {
                let estimatedSteps = metrics.totalDistance / strideLength
                let duration = max(1.0, endDate.timeIntervalSince(startDate))
                let cadencePerMinute = (estimatedSteps / duration) * 60.0
                print("   👟 Estimated steps from GPS distance: \(String(format: "%.0f", estimatedSteps)) steps (distance \(String(format: "%.2f", metrics.totalDistance))m, stride \(String(format: "%.2f", strideLength))m)")
                print("   👟 Estimated cadence from GPS steps: \(String(format: "%.1f", cadencePerMinute)) spm")
                if nativeSteps > 0 {
                    let ratio = nativeSteps > 0 ? (estimatedSteps / nativeSteps) : 0
                    print("   👟 Native vs GPS-estimated step ratio: \(String(format: "%.2f", ratio))x")
                }
                stepSources.append((estimatedSteps, "gps-estimated"))
            }

            finish(withStepSources: stepSources)
        }
    }

    private func makeDistributedStepSamples(
        stepType: HKQuantityType,
        totalSteps: Double,
        startDate: Date,
        endDate: Date
    ) -> [HKQuantitySample] {
        let duration = endDate.timeIntervalSince(startDate)
        guard duration > 0, totalSteps > 0 else { return [] }

        // Split into ~1 minute windows so HealthKit receives movement-like step blocks.
        let bucketCount = max(1, min(240, Int(duration / 60.0)))
        guard bucketCount > 1 else { return [] }

        var stepSamples: [HKQuantitySample] = []
        let bucketDuration = duration / Double(bucketCount)
        var remainingSteps = totalSteps

        for index in 0..<bucketCount {
            let bucketStart = startDate.addingTimeInterval(Double(index) * bucketDuration)
            let bucketEnd = (index == bucketCount - 1)
                ? endDate
                : startDate.addingTimeInterval(Double(index + 1) * bucketDuration)

            let stepsForBucket: Double
            if index == bucketCount - 1 {
                stepsForBucket = max(0, remainingSteps)
            } else {
                let evenShare = totalSteps / Double(bucketCount)
                stepsForBucket = max(0, evenShare)
                remainingSteps -= stepsForBucket
            }

            guard stepsForBucket > 0, bucketEnd > bucketStart else { continue }

            let sample = HKQuantitySample(
                type: stepType,
                quantity: HKQuantity(unit: .count(), doubleValue: stepsForBucket),
                start: bucketStart,
                end: bucketEnd,
                metadata: autoGeneratedSampleMetadata
            )
            stepSamples.append(sample)
        }

        return stepSamples
    }

    func addDistanceSamplesIfMissing(
        to builder: HKWorkoutBuilder,
        metrics: FlightMetrics,
        startDate: Date,
        endDate: Date,
        activityType: HKWorkoutActivityType,
        completion: @escaping () -> Void
    ) {
        guard metrics.totalDistance > 0 else {
            completion()
            return
        }

        let targetDistance = metrics.totalDistance
        let distanceIdentifiers: [HKQuantityTypeIdentifier] = {
            switch activityType {
            case .cycling, .running, .walking, .hiking:
                return [.distanceCycling, .distanceWalkingRunning]
            default:
                return [.distanceWalkingRunning]
            }
        }()
        var distanceSources: [(label: String, value: Double)] = [("gps", targetDistance)]
        if let nativeStepDistance = metrics.nativeStepDistance, nativeStepDistance > 0 {
            distanceSources.append(("nativeStep", nativeStepDistance))
        }

        var distanceSamples: [HKQuantitySample] = []
        for source in distanceSources {
            for identifier in distanceIdentifiers {
                guard let distanceType = HKQuantityType.quantityType(forIdentifier: identifier) else { continue }
                let distanceSample = HKQuantitySample(
                    type: distanceType,
                    quantity: HKQuantity(unit: .meter(), doubleValue: source.value),
                    start: startDate,
                    end: endDate,
                    metadata: autoGeneratedSampleMetadata
                )
                distanceSamples.append(distanceSample)
            }
        }

        guard !distanceSamples.isEmpty else {
            completion()
            return
        }

        let identifierText = distanceIdentifiers.map { "\($0)" }.joined(separator: ", ")
        let sourceText = distanceSources.map { "\($0.label)=\(String(format: "%.2f", $0.value))m" }.joined(separator: ", ")
        print("⌚ 📏 Adding distance sample(s) for Health app totals [\(identifierText)] from [\(sourceText)]")
        builder.add(distanceSamples) { success, error in
            if success {
                print("⌚ ✅ Distance sample(s) added successfully - will count toward Health totals")
            } else {
                print("⌚ ❌ Failed to add distance sample(s): \(error?.localizedDescription ?? "Unknown")")
            }
            completion()
        }
    }

    // Legacy method kept for fallback save path
    func addDistanceAndEnergySamples(
        to builder: HKWorkoutBuilder,
        metrics: FlightMetrics,
        startDate: Date,
        endDate: Date,
        activityType: HKWorkoutActivityType,
        completion: @escaping () -> Void
    ) {
        print("⌚ 📊 addDistanceAndEnergySamples called (fallback path):")
        print("   Total Distance: \(String(format: "%.2f", metrics.totalDistance))m (\(String(format: "%.3f", metrics.totalDistance/1000))km)")
        print("   Calories: \(String(format: "%.0f", metrics.caloriesBurned)) kcal")
        print("   Activity Type: \(activityType.rawValue) (\(activityType == .walking ? "Walking" : activityType == .running ? "Running" : activityType == .cycling ? "Cycling" : "Other"))")

        var samples: [HKQuantitySample] = []
        if metrics.totalDistance > 0 {
            let distanceTypes: [HKQuantityTypeIdentifier]
            switch activityType {
            case .running, .walking, .hiking, .cycling:
                // Keep cycling distance and mirror to walking/running totals.
                distanceTypes = [.distanceCycling, .distanceWalkingRunning]
                print("   ⚠️ Will use .distanceCycling + .distanceWalkingRunning mirror")
            default:
                distanceTypes = [.distanceWalkingRunning]
                print("   ✅ Will use .distanceWalkingRunning (default)")
            }

            var distanceSources: [(label: String, value: Double)] = [("gps", metrics.totalDistance)]
            if let nativeStepDistance = metrics.nativeStepDistance, nativeStepDistance > 0 {
                distanceSources.append(("nativeStep", nativeStepDistance))
            }

            let sourceText = distanceSources.map { "\($0.label)=\(String(format: "%.2f", $0.value))m" }.joined(separator: ", ")
            print("   📏 Distance sources: \(sourceText)")

            for source in distanceSources {
                for distanceType in distanceTypes {
                    guard let distanceSampleType = HKQuantityType.quantityType(forIdentifier: distanceType) else { continue }
                    let distanceSample = HKQuantitySample(
                        type: distanceSampleType,
                        quantity: HKQuantity(unit: .meter(), doubleValue: source.value),
                        start: startDate,
                        end: endDate,
                        metadata: autoGeneratedSampleMetadata
                    )
                    samples.append(distanceSample)
                }
            }
        }

        if metrics.caloriesBurned > 0 {
            if let energyType = HKQuantityType.quantityType(forIdentifier: .activeEnergyBurned) {
                let energySample = HKQuantitySample(
                    type: energyType,
                    quantity: HKQuantity(unit: .kilocalorie(), doubleValue: metrics.caloriesBurned),
                    start: startDate,
                    end: endDate,
                    metadata: autoGeneratedSampleMetadata
                )
                samples.append(energySample)
            }
        }

        if metrics.restingEnergyBurned > 0 {
            if let basalType = HKQuantityType.quantityType(forIdentifier: .basalEnergyBurned) {
                let basalSample = HKQuantitySample(
                    type: basalType,
                    quantity: HKQuantity(unit: .kilocalorie(), doubleValue: metrics.restingEnergyBurned),
                    start: startDate,
                    end: endDate,
                    metadata: autoGeneratedSampleMetadata
                )
                samples.append(basalSample)
            }
        }

        // Add step count ONLY when native pedometer steps are available (all activity types)
        if let stepType = HKQuantityType.quantityType(forIdentifier: .stepCount) {
            if let actualSteps = metrics.stepsCount, actualSteps > 0 {
                let stepSample = HKQuantitySample(
                    type: stepType,
                    quantity: HKQuantity(unit: .count(), doubleValue: actualSteps),
                    start: startDate,
                    end: endDate,
                    metadata: autoGeneratedSampleMetadata
                )
                samples.append(stepSample)
            } else {
                print("⌚ 👟 No native pedometer steps available - skipping step sample")
            }
        }

        guard !samples.isEmpty else {
            print("⌚ ⚠️ No distance/energy samples to add (samples array is empty)")
            print("   This means totalDistance=\(metrics.totalDistance) or caloriesBurned=\(metrics.caloriesBurned) were 0")
            completion()
            return
        }

        print("⌚ 📊 About to add \(samples.count) distance/energy/step samples:")
        for sample in samples {
            if sample.quantityType == HKQuantityType.quantityType(forIdentifier: .distanceWalkingRunning) {
                let distance = sample.quantity.doubleValue(for: .meter())
                print("   ✅ Walking/Running Distance: \(String(format: "%.2f", distance/1000))km")
            } else if sample.quantityType == HKQuantityType.quantityType(forIdentifier: .distanceCycling) {
                let distance = sample.quantity.doubleValue(for: .meter())
                print("   🚴 Cycling Distance: \(String(format: "%.2f", distance/1000))km")
            } else if sample.quantityType == HKQuantityType.quantityType(forIdentifier: .activeEnergyBurned) {
                let calories = sample.quantity.doubleValue(for: .kilocalorie())
                print("   🔥 Active Energy: \(String(format: "%.0f", calories)) kcal")
            } else if sample.quantityType == HKQuantityType.quantityType(forIdentifier: .stepCount) {
                let steps = sample.quantity.doubleValue(for: .count())
                print("   👟 Step Count: \(String(format: "%.0f", steps)) steps")
            }
        }

        builder.add(samples) { success, error in
            if success {
                print("⌚ ✅ Distance/energy/step samples added successfully")
            } else {
                print("⌚ ❌ Failed to add distance/energy/step samples: \(error?.localizedDescription ?? "Unknown")")
            }
            completion()
        }
    }

    private func buildSpeedSamples(metrics: FlightMetrics, activityType: HKWorkoutActivityType) -> [HKQuantitySample] {
        let speedTypeIdentifier: HKQuantityTypeIdentifier
        switch activityType {
        case .running, .walking, .hiking:
            speedTypeIdentifier = .runningSpeed
        case .cycling:
            speedTypeIdentifier = .cyclingSpeed
        default:
            speedTypeIdentifier = .cyclingSpeed
        }

        guard let speedType = HKQuantityType.quantityType(forIdentifier: speedTypeIdentifier) else {
            print("⌚ ⚠️ Speed type not available")
            return []
        }

        let samplingInterval = max(1, metrics.speedHistory.count / 100)
        var speedSamples: [HKQuantitySample] = []

        for (index, speedSample) in metrics.speedHistory.enumerated() where index % samplingInterval == 0 {
            // Validate speed value
            guard speedSample.speed >= 0 && speedSample.speed < 1000 else {
                print("⌚ ⚠️ Invalid speed value: \(speedSample.speed) - skipping")
                continue
            }

            let speedQuantity = HKQuantity(unit: HKUnit.meter().unitDivided(by: .second()), doubleValue: speedSample.speed)

            let sample = HKQuantitySample(
                type: speedType,
                quantity: speedQuantity,
                start: speedSample.timestamp,
                end: speedSample.timestamp.addingTimeInterval(1.0)
            )

            speedSamples.append(sample)
        }

        return speedSamples
    }

    private func buildAdvancedMetricSamples(
        metrics: FlightMetrics,
        activityType: HKWorkoutActivityType,
        locations: [FlightLocation]
    ) -> [HKQuantitySample] {
        var allSamples: [HKQuantitySample] = []
        let samplingInterval = max(1, metrics.speedHistory.count / 100)

        if let cadenceSamples = calculateCadenceSamples(
            metrics: metrics,
            activityType: activityType,
            samplingInterval: samplingInterval
        ) {
            allSamples.append(contentsOf: cadenceSamples)
        }

        if activityType == .running || activityType == .walking || activityType == .hiking || activityType == .other {
            if let strideSamples = calculateStrideLengthSamples(
                metrics: metrics,
                activityType: activityType,
                samplingInterval: samplingInterval
            ) {
                allSamples.append(contentsOf: strideSamples)
            }

            if let powerSamples = calculateRunningPowerSamples(
                metrics: metrics,
                locations: locations,
                samplingInterval: samplingInterval
            ) {
                allSamples.append(contentsOf: powerSamples)
            }

            if let vertOscSamples = calculateVerticalOscillationSamples(
                metrics: metrics,
                locations: locations,
                samplingInterval: samplingInterval
            ) {
                allSamples.append(contentsOf: vertOscSamples)
            }

            if let gctSamples = calculateGroundContactTimeSamples(metrics: metrics, samplingInterval: samplingInterval) {
                allSamples.append(contentsOf: gctSamples)
            }
        }

        return allSamples
    }

    // MARK: - Metric Calculations

    private func calculateCadenceSamples(metrics: FlightMetrics, activityType: HKWorkoutActivityType, samplingInterval: Int) -> [HKQuantitySample]? {
        var samples: [HKQuantitySample] = []

        switch activityType {
        case .running, .walking, .hiking:
            // CRITICAL FIX: stepCount requires .count() unit, NOT count/min
            // Skip step cadence samples to avoid HealthKit validation error
            print("⌚ ⚠️ Skipping step cadence samples (not compatible with stepCount cumulative type)")
            return nil

        case .cycling:
            // cyclingCadence DOES support count/min unit
            guard let cadenceType = HKQuantityType.quantityType(forIdentifier: .cyclingCadence) else { return nil }

            for (index, speedSample) in metrics.speedHistory.enumerated() where index % samplingInterval == 0 {
                let cadence = estimateCyclingCadence(speed: speedSample.speed)

                let quantity = HKQuantity(unit: HKUnit.count().unitDivided(by: .minute()), doubleValue: cadence)
                let sample = HKQuantitySample(
                    type: cadenceType,
                    quantity: quantity,
                    start: speedSample.timestamp,
                    end: speedSample.timestamp.addingTimeInterval(60.0)
                )
                samples.append(sample)
            }

        default:
            return nil
        }

        return samples.isEmpty ? nil : samples
    }

    private func calculateStrideLengthSamples(
        metrics: FlightMetrics,
        activityType: HKWorkoutActivityType,
        samplingInterval: Int
    ) -> [HKQuantitySample]? {
        let identifier: HKQuantityTypeIdentifier = {
            switch activityType {
            case .walking, .hiking:
                return .walkingStepLength
            default:
                return .runningStrideLength
            }
        }()
        guard let strideType = HKQuantityType.quantityType(forIdentifier: identifier) else { return nil }

        var samples: [HKQuantitySample] = []

        for (index, speedSample) in metrics.speedHistory.enumerated() where index % samplingInterval == 0 {
            let strideLength = calculateStrideLength(speed: speedSample.speed)

            let quantity = HKQuantity(unit: .meter(), doubleValue: strideLength)
            let sample = HKQuantitySample(
                type: strideType,
                quantity: quantity,
                start: speedSample.timestamp,
                end: speedSample.timestamp.addingTimeInterval(1.0)
            )
            samples.append(sample)
        }

        if !samples.isEmpty {
            print("⌚ 👟 Added \(samples.count) stride samples using \(identifier == .walkingStepLength ? "walkingStepLength" : "runningStrideLength")")
        }
        return samples.isEmpty ? nil : samples
    }

    private func calculateRunningPowerSamples(metrics: FlightMetrics, locations: [FlightLocation], samplingInterval: Int) -> [HKQuantitySample]? {
        guard let powerType = HKQuantityType.quantityType(forIdentifier: .runningPower) else { return nil }

        var samples: [HKQuantitySample] = []

        for (index, speedSample) in metrics.speedHistory.enumerated() where index % samplingInterval == 0 {
            let altitude = index < locations.count ? locations[index].altitude : 0.0
            let power = estimateRunningPower(speed: speedSample.speed, altitude: altitude)

            let quantity = HKQuantity(unit: .watt(), doubleValue: power)
            let sample = HKQuantitySample(
                type: powerType,
                quantity: quantity,
                start: speedSample.timestamp,
                end: speedSample.timestamp.addingTimeInterval(1.0)
            )
            samples.append(sample)
        }

        return samples.isEmpty ? nil : samples
    }

    private func calculateVerticalOscillationSamples(metrics: FlightMetrics, locations: [FlightLocation], samplingInterval: Int) -> [HKQuantitySample]? {
        guard let vertOscType = HKQuantityType.quantityType(forIdentifier: .runningVerticalOscillation) else { return nil }

        var samples: [HKQuantitySample] = []

        for (index, speedSample) in metrics.speedHistory.enumerated() where index % samplingInterval == 0 {
            let vertOsc = estimateVerticalOscillation(speed: speedSample.speed)

            let quantity = HKQuantity(unit: HKUnit.meterUnit(with: .centi), doubleValue: vertOsc)
            let sample = HKQuantitySample(
                type: vertOscType,
                quantity: quantity,
                start: speedSample.timestamp,
                end: speedSample.timestamp.addingTimeInterval(1.0)
            )
            samples.append(sample)
        }

        return samples.isEmpty ? nil : samples
    }

    private func calculateGroundContactTimeSamples(metrics: FlightMetrics, samplingInterval: Int) -> [HKQuantitySample]? {
        guard let gctType = HKQuantityType.quantityType(forIdentifier: .runningGroundContactTime) else { return nil }

        var samples: [HKQuantitySample] = []

        for (index, speedSample) in metrics.speedHistory.enumerated() where index % samplingInterval == 0 {
            let gct = estimateGroundContactTime(speed: speedSample.speed)

            let quantity = HKQuantity(unit: HKUnit.secondUnit(with: .milli), doubleValue: gct)
            let sample = HKQuantitySample(
                type: gctType,
                quantity: quantity,
                start: speedSample.timestamp,
                end: speedSample.timestamp.addingTimeInterval(1.0)
            )
            samples.append(sample)
        }

        return samples.isEmpty ? nil : samples
    }

    // MARK: - Estimation Algorithms

    private func estimateStepCadence(speed: Double, activityType: HKWorkoutActivityType) -> Double {
        let speedKmh = speed * 3.6

        switch activityType {
        case .running:
            if speedKmh < 6.0 {
                return 150.0
            } else if speedKmh < 10.0 {
                return 160.0 + (speedKmh - 6.0) * 2.5
            } else if speedKmh < 15.0 {
                return 170.0 + (speedKmh - 10.0) * 2.0
            } else {
                return 180.0
            }

        case .walking, .hiking:
            if speedKmh < 3.0 {
                return 100.0
            } else if speedKmh < 5.0 {
                return 100.0 + (speedKmh - 3.0) * 10.0
            } else {
                return 120.0
            }

        default:
            return 160.0
        }
    }

    private func estimateCyclingCadence(speed: Double) -> Double {
        let speedKmh = speed * 3.6

        if speedKmh < 15.0 {
            return 60.0
        } else if speedKmh < 25.0 {
            return 60.0 + (speedKmh - 15.0) * 2.0
        } else if speedKmh < 35.0 {
            return 80.0 + (speedKmh - 25.0) * 1.0
        } else {
            return 90.0
        }
    }

    private func calculateStrideLength(speed: Double) -> Double {
        let assumedCadence = 160.0 / 60.0

        if speed < 0.1 {
            return 0.0
        }

        let strideLength = speed / assumedCadence
        return max(0.5, min(2.5, strideLength))
    }

    private func estimateRunningPower(speed: Double, altitude: Double) -> Double {
        let mass = 70.0
        let gravity = 9.81
        let efficiency = 0.25

        let horizontalPower = mass * pow(speed, 2.0) / efficiency
        let verticalSpeed = 0.0
        let verticalPower = mass * gravity * verticalSpeed

        let totalPower = horizontalPower + verticalPower

        return max(0.0, min(500.0, totalPower))
    }

    private func estimateVerticalOscillation(speed: Double) -> Double {
        let speedKmh = speed * 3.6

        if speedKmh < 6.0 {
            return 7.0
        } else if speedKmh < 12.0 {
            return 7.0 + (speedKmh - 6.0) * 0.5
        } else if speedKmh < 18.0 {
            return 10.0 + (speedKmh - 12.0) * 0.5
        } else {
            return 13.0
        }
    }

    private func estimateGroundContactTime(speed: Double) -> Double {
        let speedKmh = speed * 3.6

        if speedKmh < 6.0 {
            return 280.0
        } else if speedKmh < 10.0 {
            return 280.0 - (speedKmh - 6.0) * 15.0
        } else if speedKmh < 15.0 {
            return 220.0 - (speedKmh - 10.0) * 10.0
        } else {
            return 170.0
        }
    }

    private func exportActivityType(_ activityType: HKWorkoutActivityType) -> HKWorkoutActivityType {
        let preference = UserDefaults.standard.string(forKey: "healthKitExportType") ?? "auto"
        switch preference {
        case "cycling":
            return .cycling
        case "running":
            return .running
        case "walking":
            return .walking
        case "hiking":
            return .hiking
        default:
            return activityType == .other ? .walking : activityType
        }
    }

    // Public method to save route to an existing workout
    func saveRoute(
        for workout: HKWorkout,
        locations: [FlightLocation],
        completion: @escaping (Bool, Error?) -> Void
    ) {
        print("⌚ 🗺️ Saving workout route for workout \(workout.uuid)...")
        print("   Workout start: \(workout.startDate), end: \(workout.endDate)")
        print("   Total locations received: \(locations.count)")

        let startBound = workout.startDate.addingTimeInterval(-5)
        let endBound = workout.endDate.addingTimeInterval(5)
        let filteredFlightLocations = locations.filter { location in
            location.isValid &&
            location.timestamp >= startBound &&
            location.timestamp <= endBound
        }

        // Convert FlightLocations to CLLocations
        let clLocations = filteredFlightLocations.map { $0.toCLLocation() }
        let filteredLocations = clLocations.filter { location in
            isCoordinateValid(location.coordinate) && location.horizontalAccuracy >= 0
        }
        print("   Converted to CLLocations: \(clLocations.count) (valid: \(filteredLocations.count))")

        // Log altitude statistics
        if !filteredLocations.isEmpty {
            let altitudes = filteredLocations.map { $0.altitude }
            let minAlt = altitudes.min() ?? 0
            let maxAlt = altitudes.max() ?? 0
            let avgAlt = altitudes.reduce(0, +) / Double(altitudes.count)
            print("   Altitude range: \(String(format: "%.1f", minAlt))m to \(String(format: "%.1f", maxAlt))m (avg: \(String(format: "%.1f", avgAlt))m)")
            print("   Sample altitudes: \(filteredLocations.prefix(3).map { String(format: "%.1f", $0.altitude) }.joined(separator: ", "))m")
        }

        // Sort locations by timestamp to ensure proper order
        let sortedLocations = filteredLocations.sorted { $0.timestamp < $1.timestamp }

        // Need at least 2 locations for a valid route
        guard sortedLocations.count >= 2 else {
            print("⌚ ❌ Not enough locations for route (need at least 2, got \(sortedLocations.count))")
            completion(false, NSError(domain: "HealthKit", code: -1, userInfo: [NSLocalizedDescriptionKey: "Not enough locations for route"]))
            return
        }

        // Log first and last location timestamps
        if let first = sortedLocations.first, let last = sortedLocations.last {
            print("   Route time span: \(first.timestamp) to \(last.timestamp)")
            print("   Route duration: \(String(format: "%.1f", last.timestamp.timeIntervalSince(first.timestamp)))s")
        }

        // Create route builder with device info
        let device = HKDevice.local()
        print("   Creating route builder with device: \(device.name ?? "Unknown")")
        let routeBuilder = HKWorkoutRouteBuilder(healthStore: healthStore, device: device)

        // Insert route data in batches for better performance
        let batchSize = 50  // Smaller batches for watchOS
        var currentIndex = 0

        func insertNextBatch() {
            let endIndex = min(currentIndex + batchSize, sortedLocations.count)
            let batch = Array(sortedLocations[currentIndex..<endIndex])

            let batchNumber = currentIndex/batchSize + 1
            let totalBatches = (sortedLocations.count + batchSize - 1) / batchSize
            print("⌚    Inserting batch \(batchNumber)/\(totalBatches): locations \(currentIndex+1) to \(endIndex)")

            routeBuilder.insertRouteData(batch) { success, error in
                if success {
                    print("⌚    ✅ Batch \(batchNumber) inserted successfully")
                    currentIndex = endIndex
                    if currentIndex < sortedLocations.count {
                        // Insert next batch
                        insertNextBatch()
                    } else {
                        // All batches inserted, finish the route
                        print("⌚    All \(sortedLocations.count) locations inserted")
                        print("⌚    Finishing route and associating with workout...")

                        routeBuilder.finishRoute(with: workout, metadata: nil) { route, error in
                            if let route = route {
                                print("⌚ ✅✅✅ Route saved successfully to HealthKit!")
                                print("   Route UUID: \(route.uuid)")
                                print("   Associated with workout: \(workout.uuid)")
                                print("   This route should now appear in the Fitness app")
                                completion(true, nil)
                            } else {
                                print("⌚ ❌ Failed to finish route: \(error?.localizedDescription ?? "Unknown")")
                                if let error = error {
                                    print("   Error code: \((error as NSError).code)")
                                    print("   Error domain: \((error as NSError).domain)")
                                }
                                completion(false, error)
                            }
                        }
                    }
                } else {
                    print("⌚ ❌ Failed to insert batch \(batchNumber): \(error?.localizedDescription ?? "Unknown")")
                    if let error = error {
                        print("   Error code: \((error as NSError).code)")
                        print("   Error domain: \((error as NSError).domain)")
                    }
                    completion(false, error)
                }
            }
        }

        // Start inserting batches
        print("⌚    Starting route data insertion...")
        insertNextBatch()
    }

    private func isCoordinateValid(_ coordinate: CLLocationCoordinate2D) -> Bool {
        let lat = coordinate.latitude
        let lon = coordinate.longitude
        return lat >= -90 && lat <= 90 && lon >= -180 && lon <= 180
    }

    private func resolveStrideLength(
        activityType: HKWorkoutActivityType,
        completion: @escaping (Double) -> Void
    ) {
        let fallbackStride = defaultStrideLength(for: activityType)

        if let cachedHeightMeters, isReasonableHeight(cachedHeightMeters) {
            completion(estimatedStrideLength(heightMeters: cachedHeightMeters, activityType: activityType))
            return
        } else if let cachedHeightMeters {
            print("   👟 Ignoring unreasonable cached height \(String(format: "%.2f", cachedHeightMeters))m - using fallback stride")
            self.cachedHeightMeters = nil
        }

        fetchLatestHeightMeters { [weak self] heightMeters in
            if let heightMeters, self?.isReasonableHeight(heightMeters) == true {
                self?.cachedHeightMeters = heightMeters
                completion(self?.estimatedStrideLength(heightMeters: heightMeters, activityType: activityType) ?? fallbackStride)
            } else {
                if let heightMeters {
                    print("   👟 Height sample looks invalid (\(String(format: "%.2f", heightMeters))m) - using fallback stride")
                } else {
                    print("   👟 Height not available - using fallback stride")
                }
                print("   👟 Fallback stride for activity \(activityType.rawValue): \(String(format: "%.2f", fallbackStride))m")
                completion(fallbackStride)
            }
        }
    }

    private func estimatedStrideLength(heightMeters: Double, activityType: HKWorkoutActivityType) -> Double {
        // Approximate stride length from height and clamp to realistic ranges.
        let factor: Double
        let minStride: Double
        let maxStride: Double
        switch activityType {
        case .running:
            factor = 0.65
            minStride = 0.80
            maxStride = 1.60
        case .walking, .hiking:
            factor = 0.415
            minStride = 0.45
            maxStride = 1.00
        default:
            factor = 0.45
            minStride = 0.50
            maxStride = 1.20
        }
        let rawStride = heightMeters * factor
        let stride = min(max(rawStride, minStride), maxStride)
        print("   👟 Height-based stride: raw=\(String(format: "%.2f", rawStride))m, clamped=\(String(format: "%.2f", stride))m (height \(String(format: "%.2f", heightMeters))m)")
        return stride
    }

    private func defaultStrideLength(for activityType: HKWorkoutActivityType) -> Double {
        switch activityType {
        case .running:
            return 1.10
        case .walking, .hiking:
            return 0.75
        default:
            return 0.85
        }
    }

    private func isReasonableHeight(_ heightMeters: Double) -> Bool {
        return heightMeters >= 1.20 && heightMeters <= 2.30
    }

    private func fetchLatestHeightMeters(completion: @escaping (Double?) -> Void) {
        guard let heightType = HKQuantityType.quantityType(forIdentifier: .height) else {
            completion(nil)
            return
        }

        let predicate = HKQuery.predicateForSamples(withStart: Date.distantPast, end: Date(), options: .strictEndDate)
        let sortDescriptor = NSSortDescriptor(key: HKSampleSortIdentifierStartDate, ascending: false)

        let query = HKSampleQuery(
            sampleType: heightType,
            predicate: predicate,
            limit: 1,
            sortDescriptors: [sortDescriptor]
        ) { _, results, error in
            if let error = error {
                print("   👟 Height query failed: \(error.localizedDescription)")
                completion(nil)
                return
            }

            guard let sample = results?.first as? HKQuantitySample else {
                completion(nil)
                return
            }

            let heightMeters = sample.quantity.doubleValue(for: .meter())
            completion(heightMeters)
        }

        healthStore.execute(query)
    }

    func fetchWorkouts(completion: @escaping ([HKWorkout]?, Error?) -> Void) {
        let workoutType = HKObjectType.workoutType()
        let sortDescriptor = NSSortDescriptor(key: HKSampleSortIdentifierStartDate, ascending: false)

        let query = HKSampleQuery(
            sampleType: workoutType,
            predicate: nil,
            limit: HKObjectQueryNoLimit,
            sortDescriptors: [sortDescriptor]
        ) { _, results, error in
            guard let workouts = results as? [HKWorkout] else {
                completion(nil, error)
                return
            }
            completion(workouts, nil)
        }

        healthStore.execute(query)
    }

    func fetchWorkout(uuid: UUID, completion: @escaping (HKWorkout?, Error?) -> Void) {
        let workoutType = HKObjectType.workoutType()
        let predicate = HKQuery.predicateForObject(with: uuid)
        let query = HKSampleQuery(
            sampleType: workoutType,
            predicate: predicate,
            limit: 1,
            sortDescriptors: nil
        ) { _, results, error in
            if let error = error {
                completion(nil, error)
                return
            }
            completion(results?.first as? HKWorkout, nil)
        }
        healthStore.execute(query)
    }

    func fetchCumulativeQuantitySum(
        for workout: HKWorkout,
        identifier: HKQuantityTypeIdentifier,
        completion: @escaping (Double?, Error?) -> Void
    ) {
        guard let quantityType = HKQuantityType.quantityType(forIdentifier: identifier) else {
            completion(nil, NSError(domain: "HealthKit", code: -1, userInfo: [NSLocalizedDescriptionKey: "Quantity type unavailable: \(identifier.rawValue)"]))
            return
        }

        let predicate = HKQuery.predicateForObjects(from: workout)
        let query = HKStatisticsQuery(
            quantityType: quantityType,
            quantitySamplePredicate: predicate,
            options: .cumulativeSum
        ) { _, result, error in
            if let error = error {
                completion(nil, error)
                return
            }
            let unit = self.unit(for: identifier)
            completion(result?.sumQuantity()?.doubleValue(for: unit), nil)
        }

        healthStore.execute(query)
    }

    private func unit(for identifier: HKQuantityTypeIdentifier) -> HKUnit {
        switch identifier {
        case .stepCount:
            return .count()
        case .distanceWalkingRunning, .distanceCycling:
            return .meter()
        case .activeEnergyBurned, .basalEnergyBurned:
            return .kilocalorie()
        default:
            return .count()
        }
    }

    func fetchRouteWithRetry(
        for workout: HKWorkout,
        maxRetries: Int = 5,
        retryDelay: TimeInterval = 1.0,
        completion: @escaping ([FlightLocation]?, Error?) -> Void
    ) {
        fetchRoute(for: workout) { [weak self] routeLocations, error in
            if let routeLocations, !routeLocations.isEmpty {
                completion(routeLocations, nil)
                return
            }

            guard maxRetries > 0, let self = self else {
                completion(nil, error ?? NSError(domain: "HealthKit", code: -1, userInfo: [NSLocalizedDescriptionKey: "Route unavailable after retries"]))
                return
            }

            DispatchQueue.global(qos: .utility).asyncAfter(deadline: .now() + retryDelay) {
                self.fetchRouteWithRetry(
                    for: workout,
                    maxRetries: maxRetries - 1,
                    retryDelay: retryDelay,
                    completion: completion
                )
            }
        }
    }

    func deleteWorkout(_ workout: HKWorkout, completion: @escaping (Bool, Error?) -> Void) {
        healthStore.delete(workout) { success, error in
            completion(success, error)
        }
    }

    func deleteWorkout(uuid: UUID, completion: @escaping (Bool, Error?) -> Void) {
        let workoutType = HKObjectType.workoutType()
        let predicate = HKQuery.predicateForObject(with: uuid)

        let query = HKSampleQuery(
            sampleType: workoutType,
            predicate: predicate,
            limit: 1,
            sortDescriptors: nil
        ) { [weak self] _, results, error in
            guard let self = self else {
                completion(false, error)
                return
            }

            if let error = error {
                completion(false, error)
                return
            }

            guard let workout = results?.first as? HKWorkout else {
                completion(true, nil)
                return
            }

            self.deleteWorkout(workout, completion: completion)
        }

        healthStore.execute(query)
    }

    func resyncFlightToHealthKit(
        flight: Flight,
        locations: [FlightLocation],
        metrics: FlightMetrics,
        completion: @escaping (Bool, Error?) -> Void
    ) {
        guard isAuthorized else {
            completion(false, NSError(domain: "HealthKit", code: -1, userInfo: [NSLocalizedDescriptionKey: "HealthKit not authorized"]))
            return
        }

        let save = {
            self.saveWorkoutWithResult(
                flight: flight,
                locations: locations,
                metrics: metrics
            ) { success, error, workout in
                if let workout = workout {
                    var updated = flight
                    updated.workoutUUID = workout.uuid
                    FlightDataStore.shared.saveFlight(updated)
                }
                completion(success, error)
            }
        }

        if let uuid = flight.workoutUUID {
            deleteWorkout(uuid: uuid) { _, _ in
                save()
            }
        } else {
            save()
        }
    }

    func fetchRoute(for workout: HKWorkout, completion: @escaping ([FlightLocation]?, Error?) -> Void) {
        print("⌚ 🗺️ Fetching route for workout: \(workout.uuid)")

        let routeType = HKSeriesType.workoutRoute()
        let predicate = HKQuery.predicateForObjects(from: workout)

        let query = HKSampleQuery(
            sampleType: routeType,
            predicate: predicate,
            limit: HKObjectQueryNoLimit,
            sortDescriptors: nil
        ) { _, results, error in
            guard let routes = results as? [HKWorkoutRoute], let route = routes.first else {
                print("⌚ ⚠️ No route found for workout")
                completion(nil, error)
                return
            }

            print("⌚ ✅ Found route, fetching location data...")

            var allLocations: [CLLocation] = []
            let routeQuery = HKWorkoutRouteQuery(route: route) { _, locations, done, error in
                if let locations = locations {
                    allLocations.append(contentsOf: locations)
                }

                if done {
                    if allLocations.isEmpty {
                        print("⌚ ⚠️ Route has no location data")
                        completion(nil, NSError(domain: "HealthKit", code: -1, userInfo: [NSLocalizedDescriptionKey: "Route has no locations"]))
                    } else {
                        print("⌚ ✅ Loaded \(allLocations.count) locations from route")

                        // Convert CLLocations to FlightLocations
                        let flightLocations = allLocations.map { location in
                            FlightLocation(from: location, isFiltered: false, isValid: true)
                        }

                        completion(flightLocations, nil)
                    }
                }
            }

            self.healthStore.execute(routeQuery)
        }

        healthStore.execute(query)
    }
}
